### ISSUE TITLE
The tailwindcss example is very wrong now

### ISSUE THREAD

**Issue by pkellner** [tailwindcss/setup-examples#112]
If I have time I'll update it, but I'm busy on some deadlines right now and don't have the time to do it.  Specifically, on the tailwindcss web page, there are details about nextjs 9 vs 10.  https://tailwindcss.com/docs/guides/nextjs

The example shows for nextjs 9.2.2.  9.5.5 had lots of problems with css and if you install the compat patch, you get a high serverity warning.  Further, you can remove the patch by taking tailwind out of the dependencies section of package.json, but still a hot mess. 

This example really needs to be updated to NextJS 10.

https://github.com/tailwindlabs/tailwindcss-setup-examples/tree/master/examples/nextjs

**Comment by adamwathan** [comment]
This whole repo is really out of date, will likely just archive it soon. Instead follow the integration guides in our documentation 👍🏻

**Comment by pkellner** [comment]
I meant to post this in nextjs, not tailwind. I assume you @adamwathan knew that.  We're you maintaining their example code?
