### ISSUE TITLE
Tailwinds not working

### ISSUE THREAD

**Issue by Parables** [tailwindcss/setup-examples#52]
I followed the steps on the README to add Tailwinds. But I don't see any effect on my elements when I add Tailwind classes. What am I doing wrong?

Here's my template: https://github.com/Parables/svelte-tailwindcss-template. 

Someone please check it out for me and point out what am missing

**Comment by adamwathan** [comment]
You missed the step where you add your compiled Tailwind CSS file to your `index.html` file:

https://github.com/tailwindcss/setup-examples/blob/master/examples/svelte/public/index.html#L13

**Comment by Parables** [comment]
Thanks very much Mr. Adam Wathan, I have added `<link rel="stylesheet" href="index.css">` to the `public/index.html` . 

When I run `npm run start:dev` I get this: 
```
  - Local:      http://localhost:5000

────────────────── LOGS ──────────────────

  [15:05:19] 200 ─ 8.32ms ─ /
  [15:05:19] 404 ─ 1.29ms ─ /bundle.css
  [15:05:19] 404 ─ 0.36ms ─ /bundle.js

```

404 means its missing right?

But I have it in my public/build directory... 
What do I do?

**Comment by Parables** [comment]
Yep, I figured I had to change:
```<link rel='stylesheet' href='bundle.css'>```   
 to    
```<link rel='stylesheet' href='build/bundle.css'>```

and 

```<script src='bundle.js'></script>```   
 to     
```<script src='build/bundle.js'></script>```

Works perfectly now :100: :+1:   :smile:  

Tailwind is simply amazing.

**Comment by Parables** [comment]
Am closing this issue now since it's been resolved
