### ISSUE TITLE
@apply not working in <style>...</style>

### ISSUE THREAD

**Issue by Parables** [tailwindcss/setup-examples#54]
Tailwind is great but I'm still stuck writing CSS because I can't use @apply directive in Svelte ... any help to resolve this?

``` 
svg {
  @apply h-8 w-8 fill-current;
}
```

**Comment by jfdelarosa** [comment]
Try using this tutorial:

https://dev.to/sarioglu/using-svelte-with-tailwindcss-a-better-approach-47ph

**Comment by Parables** [comment]
Am sorry okay, I forgot to close this issue. I found out about that repo later that day and even made my own template using parcel
