### ISSUE TITLE
tailwindcss + next.js + emotion.js example

### ISSUE THREAD

**Issue by theairbend3r** [tailwindcss/setup-examples#58]
Hi!

I love explanation in the tailwindcss + next example! :)

Can we add emotion.js to that example? I think the community would benefit from an explanation about the setup. 

Let me know your thoughts. :)

**Comment by fvaldes33** [comment]
They have an example for this in the nextjs examples

[nextjs/with-tailwindcss-emotion](https://github.com/zeit/next.js/tree/canary/examples/with-tailwindcss-emotion)
